x-airflow-common:
  &airflow-common
  build:
    context: .
    dockerfile: Dockerfile
  image: airbnb-airflow:latest
  environment:
    &airflow-common-env
    AIRFLOW__API_AUTH__JWT_SECRET: ${AIRFLOW__API_AUTH__JWT_SECRET}
    AIRFLOW__CORE__EXECUTOR: ${AIRFLOW_EXECUTOR}
    AIRFLOW__CORE__AUTH_MANAGER: ${AIRFLOW__CORE__AUTH_MANAGER}
    AIRFLOW__CORE__EXECUTION_API_SERVER_URL: 'http://airflow-apiserver:8080/execution/'
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
    AIRFLOW__SCHEDULER__ENABLE_HEALTH_CHECK: "true"
  volumes:
    - ${AIRFLOW_DATA}:/opt/airflow/data
    - ${AIRFLOW_DAGS}:/opt/airflow/dags
    - ${AIRFLOW_LOGS}:/opt/airflow/logs
    - ${AIRFLOW_PLUGINS}:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  networks:
    - app-network
  depends_on:
    postgres:
      condition: service_healthy

services:
  postgres:
    image: postgres:${POSTGRES_IMAGE_VERSION}
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
      interval: 5s
      retries: 5
      start_period: 5s
    restart: always
    networks:
      - app-network

  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    command: ["bash", "-c", "airflow db migrate"]
    environment:
      <<: *airflow-common-env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  airflow-apiserver:
    <<: *airflow-common
    container_name: airflow-apiserver
    command: api-server
    ports:
      - ${AIRFLOW_WEB_SERVER_PORT}:8080
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/api/v2/version"]
      interval: 1800s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - app-network
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8974/health"]
      interval: 1800s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    networks:
      - app-network
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      airflow-apiserver:
        condition: service_healthy

  airflow-dag-processor:
    <<: *airflow-common
    container_name: airflow-dag-processor
    command: dag-processor
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type DagProcessorJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully
      airflow-apiserver:
        condition: service_healthy

  airflow-triggerer:
    <<: *airflow-common
    command: triggerer
    healthcheck:
      test: ["CMD-SHELL", 'airflow jobs check --job-type TriggererJob --hostname "$${HOSTNAME}"']
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    restart: always
    depends_on:
      airflow-init:
        condition: service_completed_successfully

  mongo:
    image: mongo:${MONGODB_IMAGE_VERSION}
    container_name: ${MONGODB_CONTAINER_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_EXPRESS_ADMINUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_EXPRESS_ADMINPASSWORD}
    ports:
      - "${MONGODB_PORT}:27017"
    restart: always
    networks:
      - app-network

  mongo-express:
    image: mongo-express:${MONGO_EXPRESS_IMAGE_VERSION}
    container_name: ${MONGO_EXPRESS_CONTAINER_NAME}
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_EXPRESS_SERVER}:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_ADMINPASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_BASIC_AUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_BASIC_AUTH_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_EXPRESS_SERVER}
    ports:
      - "${MONGO_EXPRESS_HOST_BIND_IP}:${MONGO_EXPRESS_PORT}:8081"
    restart: always
    networks:
      - app-network
    depends_on:
      - mongo

volumes:
  pg-data:
    name: ${POSTGRES_VOLUME}

networks:
  app-network:
    name: ${NETWORK_NAME}
