x-airflow-common:
  &airflow-common
  image: apache/airflow:${AIRFLOW_IMAGE_VERSION}
  environment:
    &airflow-common-env
    AIRFLOW_EXECUTOR: ${AIRFLOW_EXECUTOR}
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN}
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__API__AUTH_BACKENDS: ${AIRFLOW__API__AUTH_BACKENDS}
  volumes:
    - ${AIRFLOW_DATA}:/opt/airflow/data
    - ${AIRFLOW_DAGS}:/opt/airflow/dags
    - ${AIRFLOW_LOGS}:/opt/airflow/logs
    - ${AIRFLOW_PLUGINS}:/opt/airflow/plugins
  user: "${AIRFLOW_UID:-50000}:0"
  networks:
    - app-network

services:
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    command: ["bash", "-c", "airflow db init && airflow db migrate"]
    environment:
      <<: *airflow-common-env
      _AIRFLOW_DB_MIGRATE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_USERNAME: ${AIRFLOW_USER_USERNAME}
      _AIRFLOW_WWW_USER_PASSWORD: ${AIRFLOW_USER_PASSWORD}
      _AIRFLOW_WWW_USER_EMAIL: ${AIRFLOW_USER_EMAIL}
      _AIRFLOW_WWW_USER_ROLE: ${AIRFLOW_USER_ROLE}
    volumes:
      - .:/sources
    depends_on:
      - postgres
    networks:
      - app-network

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    command: webserver
    environment:
      <<: *airflow-common-env 
    ports:
      - ${AIRFLOW_WEB_SERVER_PORT}:8080
    restart: always
    networks:
      - app-network
    depends_on:
      - airflow-init

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: scheduler
    environment:
      <<: *airflow-common-env
    restart: always
    networks:
      - app-network
    depends_on:
      - airflow-init

  postgres:
    image: postgres:${POSTGRES_IMAGE_VERSION}
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    restart: always
    networks:
      - app-network
  
  mongo:
    image: mongo:${MONGODB_IMAGE_VERSION}
    container_name: ${MONGODB_CONTAINER_NAME}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_EXPRESS_ADMINUSERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_EXPRESS_ADMINPASSWORD}
    ports:
      - "${MONGODB_PORT}:27017"
    restart: always
    networks:
      - app-network
  
  mongo-express:
    image: mongo-express:${MONGO_EXPRESS_IMAGE_VERSION}
    container_name: ${MONGO_EXPRESS_CONTAINER_NAME}
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_EXPRESS_SERVER}:27017/
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_EXPRESS_ADMINUSERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_EXPRESS_ADMINPASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${MONGO_EXPRESS_BASIC_AUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${MONGO_EXPRESS_BASIC_AUTH_PASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${MONGO_EXPRESS_SERVER}
    ports:
      - "${MONGO_EXPRESS_HOST_BIND_IP}:${MONGO_EXPRESS_PORT}:8081"
    restart: always
    networks:
      - app-network
    depends_on:
      - mongo

volumes:
  postgres-data:

networks:
  app-network:
    name: ${NETWORK_NAME}